#!/bin/sh
echo "Which user would you like to tej ?"
read username

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

check_exist=`cat /etc/passwd | grep $username`
if [ "$check_exist" != "$NULL" ]; then
	sudo passwd -l $username
	if [ "$(pgrep -u $username)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $username)
	fi
	sudo userdel -r $username
	echo "${green}USER WAS SUCCESSFULLY TEJ :-)"
else
	echo "${red}user doesn't exist"
fi